phase2/project/config/routes.rb
Rails.application.routes.draw do
  resources :vegetarians
  resources :mexicans
  resources :japaneses
  resources :frenches
  resources :chineses
  resources :canadianposts
  resources :foodtypes
  get 'sessions/new'
  resources :microposts
  get 'static_pages/home'
  get 'static_pages/menu'
  get 'static_pages/help'
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  root 'static_pages#home'

   resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

phase2/project/app/models/canadianpost.rb
class Canadianpost < ActiveRecord::Base
end

phase2/project/app/models/chinese.rb
class Chinese < ActiveRecord::Base
end

phase2/project/app/models/foodtype.rb
class Foodtype < ActiveRecord::Base
end

phase2/project/app/models/french.rb
class French < ActiveRecord::Base
end

phase2/project/app/models/japanese.rb
class Japanese < ActiveRecord::Base
end

phase2/project/app/models/mexican.rb
class Mexican < ActiveRecord::Base
end

phase2/project/app/models/micropost.rb
class Micropost < ActiveRecord::Base
    serialize :list_of_user_id,Array
    belongs_to :user
    validates :content,  presence: true, length: { maximum: 150 }
    validates :location,  presence: true, length: { maximum: 150 }
    mount_uploader :picture, PictureUploader
    validates :foodtype,  presence: true, length: { maximum: 50 }
    default_scope {order('microposts.created_at DESC')}
end

phase2/project/app/models/user.rb
class User < ActiveRecord::Base
   serialize :list_of_micropost_id,Array
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  mount_uploader :picture, PictureUploader
  validates :password, presence: true, length: { minimum: 6 }
  has_many :microposts
  
  acts_as_messageable

  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end
  
  def picture_size
    if picture.size>5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

phase2/project/app/models/vegetarian.rb
class Vegetarian < ActiveRecord::Base
end

phase2/project/app/controllers/canadianposts_controller.rb
class CanadianpostsController < ApplicationController
  before_action :set_canadianpost, only: [:show, :edit, :update, :destroy]

  # GET /canadianposts
  # GET /canadianposts.json
  def index
    @canadianposts = Canadianpost.all
    @microposts = Micropost.all
    if params[:status]
      a = Micropost.find(params[:status])
      a.status = a.status - 1
      a.save
      @user = current_user
      @user.update_attribute(:list_of_micropost_id, @user.list_of_micropost_id << a.id)
      a.update_attribute(:list_of_user_id, a.list_of_user_id << @user.id)
      a.save
      @user.save
      
    end
    if logged_in?
      @user = current_user
      @user_post_id = @user.id
      @user_list_of_micropost_id = @user.list_of_micropost_id
      @reserve_id = []
      for micropost in Micropost.all
        if  not @user.list_of_micropost_id.include?(micropost.id)
          @reserve_id.push(micropost.id)
        end
      end
    else
      @reserve_id = []
      @user_list_of_micropost_id = []
      @user = current_user
      @user_post_id = 0
    end
    @microposts = Micropost.all

    @location = []
    @user_id = []
    @content = []
    @foodtype = []
    for mp in Micropost.all
      if mp.foodtype == 'Canadian'
        @location.push(mp.location)
        @content.push(mp.content)
        @user_id.push(mp.user_id)
        @foodtype.push(mp.foodtype)
      end
    end
    
    @user_name = []
      for id in @user_id
        @user_name.push((User.find(id)).name)
      end


  end

  # GET /canadianposts/1
  # GET /canadianposts/1.json
  def show
  end

  # GET /canadianposts/new
  def new
    @canadianpost = Canadianpost.new
  end

  # GET /canadianposts/1/edit
  def edit
  end

  # POST /canadianposts
  # POST /canadianposts.json
  def create
    @canadianpost = Canadianpost.new(canadianpost_params)

    respond_to do |format|
      if @canadianpost.save
        format.html { redirect_to @canadianpost, notice: 'Canadianpost was successfully created.' }
        format.json { render :show, status: :created, location: @canadianpost }
      else
        format.html { render :new }
        format.json { render json: @canadianpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /canadianposts/1
  # PATCH/PUT /canadianposts/1.json
  def update
    respond_to do |format|
      if @canadianpost.update(canadianpost_params)
        format.html { redirect_to @canadianpost, notice: 'Canadianpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @canadianpost }
      else
        format.html { render :edit }
        format.json { render json: @canadianpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /canadianposts/1
  # DELETE /canadianposts/1.json
  def destroy
    @canadianpost.destroy
    respond_to do |format|
      format.html { redirect_to canadianposts_url, notice: 'Canadianpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_canadianpost
      @canadianpost = Canadianpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def canadianpost_params
      params.require(:canadianpost).permit(:content, :user_id, :status, :location, :foodtype, :picture, :list_of_user_id)
    end
end

phase2/project/app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
  def active_page(active_page)
    @active == active_page ? "active" : ""
  end
  
end

phase2/project/app/helpers/canadianposts_helper.rb
module CanadianpostsHelper
end

phase2/project/app/helpers/chineses_helper.rb
module ChinesesHelper
end

phase2/project/app/helpers/foodtypes_helper.rb
module FoodtypesHelper
end

phase2/project/app/helpers/frenches_helper.rb
module FrenchesHelper
end

phase2/project/app/helpers/japaneses_helper.rb
module JapanesesHelper
end

phase2/project/app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

phase2/project/app/helpers/mexicans_helper.rb
module MexicansHelper
end

phase2/project/app/helpers/microposts_helper.rb
module MicropostsHelper
end

phase2/project/app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
      session[:user_id] = user.id
    end
    
     # 返回当前登录的用户（如果有的话）
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

  # 如果用户已登录，返回 true，否则返回 false
    def logged_in?
      !current_user.nil?
    end
    
    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
    
    def current_user?(user)
      user == current_user
    end
    
    def redirect_back_or(default)
      redirect_to(session[:forwarding_url] || default)
      session.delete(:forwarding_url)
    end
    
    def store_location
      session[:forwarding_url] = request.url if request.get?
    end
end

phase2/project/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

phase2/project/app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

phase2/project/app/helpers/vegetarians_helper.rb
module VegetariansHelper
end

phase2/project/app/views/canadianposts/_form.html.erb
<%= form_for(@canadianpost) do |f| %>
  <% if @canadianpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@canadianpost.errors.count, "error") %> prohibited this canadianpost from being saved:</h2>

      <ul>
      <% @canadianpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :foodtype %><br>
    <%= f.text_field :foodtype %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :list_of_user_id %><br>
    <%= f.text_field :list_of_user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

phase2/project/app/views/canadianposts/edit.html.erb
<h1>Editing Canadianpost</h1>

<%= render 'form' %>

<%= link_to 'Show', @canadianpost %> |
<%= link_to 'Back', canadianposts_path %>

phase2/project/app/views/canadianposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Canadianposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Status</th>
      <th>Location</th>
      <th>Foodtype</th>
      <th>user_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
     <% if micropost.foodtype == 'Canadian' and micropost.status > 0 %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.status %></td>
        <td><%= micropost.location %></td>
        <td><%= micropost.foodtype %></td>
        <td><%= micropost.user_id %></td>
        <% @user_list_of_micropost_id.each do |postid| %>
          <% if micropost.id ==postid && @user_post_id != 0 && micropost.user_id != @user_post_id%>
            <td><%= link_to("Check Your Reservation",'/microposts/'+micropost.id.to_s)%></td>
          <% end %>
        <% end %>
        
         <% @reserve_id.each do |postid| %>
          <% if micropost.id == postid && @user_post_id != 0 && micropost.user_id != @user_post_id%>
            <td><%= link_to("Reserve Now!",'/microposts?status='+micropost.id.to_s)%></td>
          <% end %>
        <% end %>
        
        
        <% if micropost.user_id == @user_post_id %>
         <td><%= link_to("Check Your Post",'/microposts/'+micropost.id.to_s)%>
        </td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'back', Micropost %>


<head>
  <style type="text/css">
    body { height: 100%; margin: 0; padding: 0; }
    #map { height: 100%; }
  </style>
</head>
  
<body>
  
  <div id="map" style="height:350px;"></div>

  
  

  <script>
    initMap();
    drawMap(<%= raw @location.to_json %>, <%= raw @user_name.to_json %>, <%= raw @user_id.to_json %>, <%= raw @content.to_json %>, <%= raw @foodtype.to_json %>);
  </script>


</body>

phase2/project/app/views/canadianposts/new.html.erb
<h1>New Canadianpost</h1>

<%= render 'form' %>

<%= link_to 'Back', canadianposts_path %>

phase2/project/app/views/canadianposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @canadianpost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @canadianpost.user_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @canadianpost.status %>
</p>

<p>
  <strong>Location:</strong>
  <%= @canadianpost.location %>
</p>

<p>
  <strong>Foodtype:</strong>
  <%= @canadianpost.foodtype %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @canadianpost.picture %>
</p>

<p>
  <strong>List of user:</strong>
  <%= @canadianpost.list_of_user_id %>
</p>

<%= link_to 'Edit', edit_canadianpost_path(@canadianpost) %> |
<%= link_to 'Back', canadianposts_path %>