phase2/project/config/routes.rb
Rails.application.routes.draw do
  resources :vegetarians
  resources :mexicans
  resources :japaneses
  resources :frenches
  resources :chineses
  resources :canadianposts
  resources :foodtypes
  get 'sessions/new'
  resources :microposts
  get 'static_pages/home'
  get 'static_pages/menu'
  get 'static_pages/help'
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  root 'static_pages#home'

   resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

phase2/project/app/models/canadianpost.rb
class Canadianpost < ActiveRecord::Base
end

phase2/project/app/models/chinese.rb
class Chinese < ActiveRecord::Base
end

phase2/project/app/models/foodtype.rb
class Foodtype < ActiveRecord::Base
end

phase2/project/app/models/french.rb
class French < ActiveRecord::Base
end

phase2/project/app/models/japanese.rb
class Japanese < ActiveRecord::Base
end

phase2/project/app/models/mexican.rb
class Mexican < ActiveRecord::Base
end

phase2/project/app/models/micropost.rb
class Micropost < ActiveRecord::Base
    serialize :list_of_user_id,Array
    belongs_to :user
    validates :content,  presence: true, length: { maximum: 150 }
    validates :location,  presence: true, length: { maximum: 150 }
    mount_uploader :picture, PictureUploader
    validates :foodtype,  presence: true, length: { maximum: 50 }
    default_scope {order('microposts.created_at DESC')}
end

phase2/project/app/models/user.rb
class User < ActiveRecord::Base
   serialize :list_of_micropost_id,Array
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  mount_uploader :picture, PictureUploader
  validates :password, presence: true, length: { minimum: 6 }
  has_many :microposts
  
  acts_as_messageable

  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end
  
  def picture_size
    if picture.size>5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

phase2/project/app/models/vegetarian.rb
class Vegetarian < ActiveRecord::Base
end

phase2/project/app/controllers/foodtypes_controller.rb
class FoodtypesController < ApplicationController
  before_action :set_foodtype, only: [:show, :edit, :update, :destroy]

  # GET /foodtypes
  # GET /foodtypes.json
  def index
    @foodtypes = Foodtype.all
    @microposts = Micropost.all

  end

  # GET /foodtypes/1
  # GET /foodtypes/1.json
  def show
  end

  # GET /foodtypes/new
  def new
    @foodtype = Foodtype.new
  end

  # GET /foodtypes/1/edit
  def edit
  end

  # POST /foodtypes
  # POST /foodtypes.json
  def create
    @foodtype = Foodtype.new(foodtype_params)

    respond_to do |format|
      if @foodtype.save
        format.html { redirect_to @foodtype, notice: 'Foodtype was successfully created.' }
        format.json { render :show, status: :created, location: @foodtype }
      else
        format.html { render :new }
        format.json { render json: @foodtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foodtypes/1
  # PATCH/PUT /foodtypes/1.json
  def update
    respond_to do |format|
      if @foodtype.update(foodtype_params)
        format.html { redirect_to @foodtype, notice: 'Foodtype was successfully updated.' }
        format.json { render :show, status: :ok, location: @foodtype }
      else
        format.html { render :edit }
        format.json { render json: @foodtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foodtypes/1
  # DELETE /foodtypes/1.json
  def destroy
    @foodtype.destroy
    respond_to do |format|
      format.html { redirect_to foodtypes_url, notice: 'Foodtype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foodtype
      @foodtype = Foodtype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foodtype_params
      params.require(:foodtype).permit(:region, :cuisine)
    end
end

phase2/project/app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
  def active_page(active_page)
    @active == active_page ? "active" : ""
  end
  
end

phase2/project/app/helpers/chineses_helper.rb
module ChinesesHelper
end

phase2/project/app/helpers/foodtypes_helper.rb
module FoodtypesHelper
end

phase2/project/app/helpers/frenches_helper.rb
module FrenchesHelper
end

phase2/project/app/helpers/japaneses_helper.rb
module JapanesesHelper
end

phase2/project/app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

phase2/project/app/helpers/mexicans_helper.rb
module MexicansHelper
end

phase2/project/app/helpers/microposts_helper.rb
module MicropostsHelper
end

phase2/project/app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
      session[:user_id] = user.id
    end
    
     # 返回当前登录的用户（如果有的话）
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

  # 如果用户已登录，返回 true，否则返回 false
    def logged_in?
      !current_user.nil?
    end
    
    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
    
    def current_user?(user)
      user == current_user
    end
    
    def redirect_back_or(default)
      redirect_to(session[:forwarding_url] || default)
      session.delete(:forwarding_url)
    end
    
    def store_location
      session[:forwarding_url] = request.url if request.get?
    end
end

phase2/project/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

phase2/project/app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

phase2/project/app/helpers/vegetarians_helper.rb
module VegetariansHelper
end

phase2/project/app/views/foodtypes/_form.html.erb
<%= form_for(@foodtype) do |f| %>
  <% if @foodtype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foodtype.errors.count, "error") %> prohibited this foodtype from being saved:</h2>

      <ul>
      <% @foodtype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :cuisine %><br>
    <%= f.text_field :cuisine %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

phase2/project/app/views/foodtypes/edit.html.erb
<h1>Editing Foodtype</h1>

<%= render 'form' %>

<%= link_to 'Show', @foodtype %> |
<%= link_to 'Back', foodtypes_path %>

phase2/project/app/views/foodtypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Foodtypes</h1>

<table>
  <thead>
    <tr>
      <th>Region</th>
      <th>Cuisine</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foodtypes.each do |foodtype| %>
      <tr>
        <td><%= foodtype.region %></td>
        <td><%= foodtype.cuisine %></td>
        <td><%= link_to 'Show', foodtype %></td>
        <td><%= link_to 'Edit', edit_foodtype_path(foodtype) %></td>
        <td><%= link_to 'Destroy', foodtype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foodtype', new_foodtype_path %>

phase2/project/app/views/foodtypes/new.html.erb
<h1>New Foodtype</h1>

<%= render 'form' %>

<%= link_to 'Back', foodtypes_path %>

phase2/project/app/views/foodtypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Region:</strong>
  <%= @foodtype.region %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @foodtype.cuisine %>
</p>

<%= link_to 'Edit', edit_foodtype_path(@foodtype) %> |
<%= link_to 'Back', foodtypes_path %>